This is makeindex, version 2.16 [MiKTeX 25.4].
Scanning style file ./Template_Thesis.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file Template_Thesis.acn....done (2 entries accepted, 0 rejected).
Sorting entries....done (2 comparisons).
Generating output file Template_Thesis.acr....done (9 lines written, 0 warnings).
Output written in Template_Thesis.acr.
Transcript written in Template_Thesis.alg.
